[project]
name = "emri_tdi_sampler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastlisaresponse>=1.1.9",
    "setuptools>=80.9.0",
    "ultranest>=4.4.0",
    "fastemriwaveforms-cuda12x>=2.0.0",
    "cupy-cuda12x>=13.6.0",
    "eryn>=1.2.3",
]

[tool.uv.sources]
fastlisaresponse = { path = "lisa-on-gpu", editable = true }
